sudo: required
language: python

env:
  global:
    - TERM=dumb
    - DOCKER_IMAGE=alectolytic/rpmbuilder
    - COPR_REPOSITORY=todo
    - OS_ARCH=x86_64
    - BASE_SVN_REVISION=7901
    - BASE_PACKAGE_VERSION=0.9.0
    - BASE_PACKAGE_DATE="Sun Feb 11 2018"
    - PRODUCTION_BRANCH=master
  matrix:
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=27

services:
  - docker

before_install:
#  - export SVN_REVISION=`svn info http://svn.code.sf.net/p/doublecmd/code/trunk --show-item revision`
# Workaround as --shot-item is not available in SVN 1.8.8
  - export SVN_REVISION=`svn info http://svn.code.sf.net/p/doublecmd/code/trunk | grep "Revision" | cut -d" " -f2`
  - echo "The latest revision in SVN - ${SVN_REVISION}"
# Manual number for now to keep version number incemented during development
  - export SVN_REVISION=7910
  - echo "Building SVN revision ${SVN_REVISION}"
  - if ! [[ "${SVN_REVISION}" =~ ^-?[0-9]+$ ]]; then travis_terminate 1; fi
  - sed -i s/"${BASE_SVN_REVISION}"/"${SVN_REVISION}"/g doublecmd-gtk.spec
  - sed -i s/"* ${BASE_PACKAGE_DATE}"/"* $(date "+%a %b %d %Y")"/g doublecmd-gtk.spec
  - git diff
# COPR credentials and cli
  - pip install copr-cli simplejson
  - if [[ "${TRAVIS_SECURE_ENV_VARS}" == "true" ]]; then
      openssl aes-256-cbc -K $encrypted_749aaf58d2e1_key -iv $encrypted_749aaf58d2e1_iv -in copr.enc -out ~/.config/copr -d || travis_terminate 1;
    fi

install:
  - svn export http://svn.code.sf.net/p/doublecmd/code/trunk doublecmd-${BASE_PACKAGE_VERSION}
  - tar caf doublecmd-${BASE_PACKAGE_VERSION}-r${SVN_REVISION}.tar.xz doublecmd-${BASE_PACKAGE_VERSION}

script:
  - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z -e "SRPM_ONLY=1" ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}
  - ls -l *.rpm
# Could be moved before RPM build process, however, having it after provided sanity tests even if no new commits are made
  - if [[ "${PRODUCTION_BRANCH}" == "${TRAVIS_BRANCH}" && "${TRAVIS_SECURE_ENV_VARS}" == "true" ]]; then
      export LAST_SUCCEEDED_BUILD_SVN_REVISION=`copr-cli get-package --name doublecmd-gtk --with-latest-succeeded-build vondruch/doublecmd | jq -r '.latest_succeeded_build.pkg_version' | gawk 'match($0, /\.svn([0-9]*)\.fc/, a) {print a[1]}'`;
      if [[ "${LAST_SUCCEEDED_BUILD_SVN_REVISION}" == '' ]]; then
        echo "Unable to find last succeeded build number";
        travis_terminate 1;
      fi;
      if [[ "${SVN_REVISION}" -gt "${LAST_SUCCEEDED_BUILD_SVN_REVISION}" ]]; then
        echo "Building code from SVN revision ${SVN_REVISION} in COPR. It may take several minutes.";
        copr-cli build vondruch/doublecmd doublecmd-gtk-${BASE_PACKAGE_VERSION}-*.src.rpm || travis_terminate 1;
      else
        echo "Skipping COPR build. Current SVN revision (${SVN_REVISION}) is not greater than previously build in COPR (${LAST_SUCCEEDED_BUILD_SVN_REVISION}).";
      fi;
    else
      echo "Skipping COPR build. Not in production branch ${PRODUCTION_BRANCH}.";
    fi;

